<?php
   return [
    "Academias",             
    "Açougue",                     
    "Acupuntura",
    "Administração",
    "Advogado",
    "Agência de Publicidade",
    "Agência de Viagens",
    "Agricultura",
    "Agricultura e Pecuária",
    "Agrônomo",
    "Aluguel de tendas",
    "Aluguel de veículos",
    "Análises Clínicas",
    "Anestesiologistas",
    "Animação",
    "Animador de Eventos",
    "Animais",
    "Antropólogo",
    "Aromaterapia",
    "Arqueólogo",
    "Arquitetos",
    "Arquitetura e Paisagismo",
    "Artes gráficas",
    "Artesanato",
    "Assistência Técnica",
    "Assistente Social",
    "Associações",
    "Associações sem fins lucrativos",
    "Astrônomo",
    "Atuário",
    "Auditor contábil",
    "Auditoria",
    "Autocad e Modelagem 3D",
    "Auto-Escolas",
    "Autores",
    "Ayurveda",
    "Babá e Babysitter",
    "Bares",
    "Beleza e Bem-Estar",
    "Bijuteria",
    "Biólogo",
    "Blog",
    "Bolos e Doces",
    "Botânico",
    "Boutique",
    "Bricolagem",
    "Buffet",
    "Business",
    "Cabeleireiro",
    "Cafés",
    "Carnaval",
    "Carpintaria",
    "Cartógrafo",
    "Casa, Obras e Jardim",
    "Casamentos e Batizados",
    "Casas de chá",
    "Certificação Energética",
    "Churrascaria",
    "Ciências",
    "Cinema",
    "Cirurgiões",
    "Coach",
    "Comerciais",
    "Comércio",
    "Comércio Tradicional",
    "Condomínios",
    "Confeitarias",
    "Conservação e Restauro",
    "Construção Civil",
    "Consultora de beleza",
    "Consultoria",
    "Contabilidade",
    "Corretores de Imóveis",
    "Corticeira",
    "Cosmética",
    "Costureiras",
    "Cozinheiro",
    "Cromoterapia",
    "Culturas e Eventos",
    "Decoração",
    "Demógrafo",
    "Dentista",
    "Depilação",
    "Dermatologista",
    "Desentupidora",
    "Desenvolvimento Sites",
    "Design",
    "Design e Tecnologia",
    "Design Gráfico",
    "Design Interiores",
    "Desinfestação",
    "DJ",
    "Doméstica",
    "Ecommerce",
    "Economista",
    "Educação",
    "Educador Social",
    "Eletricista",
    "Empresa",
    "Empresa de Eventos",
    "Encanadores",
    "Endocrinologistas",
    "Enfermeiros",
    "Engenharia",
    "Engenheiro",
    "Engenheiro Agrônomo",
    "Engenheiro Ambiental",
    "Engenheiro Civil",
    "Engenheiro de Mineração",
    "Engenheiro de Produção",
    "Engenheiro de Telecomunicações",
    "Engenheiro Elétrico",
    "Engenheiro Florestal",
    "Engenheiro Industrial",
    "Engenheiro Mecânico",
    "Engenheiro Mecatrônico",
    "Engenheiro Metalúrgico",
    "Engenheiro Químico",
    "Engomadoria",
    "Enólogo",
    "Especialidades",
    "Estatístico",
    "Esteticista",
    "Estilista",
    "Estomatologista",
    "Estucador",
    "Eventos",
    "Explicadores",
    "Farmacêutico",
    "Farmácias",
    "Ferragens",
    "Festas",
    "Festas de Aniversário",
    "Filólogo",
    "Filósofo",
    "Fiscalização",
    "Físico",
    "Fisioterapia",
    "Fitoterapia",
    "Florais de Bach",
    "Florista",
    "Fonoaudiólogos",
    "Fotógrafo",
    "Freelancer",
    "Funerárias",
    "Galerias de arte",
    "Gastroenterologistas",
    "Geneticistas",
    "Geofísico",
    "Geógrafo",
    "Geólogo",
    "Gerontologista",
    "Gestão",
    "Gestão de Redes Sociais",
    "Ginecologistas",
    "Gráfica",
    "Grafismo",
    "Grandes Empresas",
    "Guias Turísticos",
    "Hematologistas",
    "Historiador",
    "Homeopata",
    "Hortifruti",
    "Hotel",
    "Ilustração",
    "Imobiliária",
    "Impressão",
    "Industria",
    "Indústria Moldes",
    "Indústria Têxtil",
    "Infectologistas",
    "Informática",
    "Instalações",
    "Instalador Gás",
    "Intérprete",
    "Iridologia",
    "Isolamentos",
    "Jardineiro",
    "Joalheria",
    "Jornal",
    "Jornalista",
    "Ladrilhador",
    "Lanchonete",
    "Lares",
    "Lavanderia",
    "Limpeza de Chaminés",
    "Limpezas",
    "Linguista",
    "Livrarias",
    "Loja de calçados",
    "Loja de Roupas",
    "Loja Infantil",
    "Lojas",
    "Lojistas",
    "Magnetoterapia",
    "Manicure e Pedicure",
    "Manutenção",
    "Maquiador",
    "Marceneiro",
    "Marketing",
    "Marketing Digital",
    "Massagista",
    "Massoterapia",
    "Matemático",
    "Mecânicos",
    "Medicina",
    "Medicinas Alternativas",
    "Mercearia",
    "Metalurgia",
    "Meteorologista",
    "Mídia",
    "Mobile",
    "Moda",
    "Modelos",
    "Motoristas",
    "Móveis e decoração",
    "Mudanças",
    "Músicos",
    "Musicoterapia",
    "Natal",
    "Neurologistas",
    "Nutricionistas",
    "Obras",
    "Oceanógrafo",
    "Oculista",
    "Oficina Mecânica",
    "Oftalmologistas",
    "Oncologistas",
    "Online",
    "Optometrista",
    "Otorrino",
    "Ourivesaria",
    "Outros",
    "Padaria",
    "Papelaria",
    "Parasitologista",
    "Patologistas",
    "Pecuária",
    "Pediatras",
    "Pedreiros",
    "Peixaria",
    "Pensões",
    "Perfumaria",
    "Personal Trainer",
    "Pesquisa de Mercado",
    "Pet Shop",
    "Pet sitter",
    "Pintura",
    "Pintura Artística",
    "Piscinas",
    "Pisos",
    "Procuradores",
    "Professor de Alemão",
    "Professor de Artes",
    "Professor de Dança",
    "Professor de Educação Física",
    "Professor de Espanhol",
    "Professor de Esportes",
    "Professor de Filosofia",
    "Professor de Francês",
    "Professor de Idiomas",
    "Professor de Inglês",
    "Professor de Matemática",
    "Professor de Música",
    "Professor Particular",
    "Professor Português",
    "Professor Universitário",
    "Professores",
    "Professores Espanhol",
    "Professores Geometria",
    "Professores Inglês",
    "Professores Matemática",
    "Professores Português",
    "Profissionais",
    "Profissões Liberais",
    "Programação e Software",
    "Psicólogo",
    "Psiquiatra",
    "Publicidade",
    "Químico",
    "Quiropraxia",
    "Rádio",
    "Radiologista",
    "Ramo automóvel",
    "Redator",
    "Reflexologia",
    "Refrigeração",
    "Reiki",
    "Relações Públicas",
    "Relojoeiro",
    "Remodelações",
    "Reparação Computadores",
    "Reparação de aparelhos eletrónicos",
    "Restauração e Hotelaria",
    "Restaurante",
    "Revenda",
    "Revista",
    "Risoterapia",
    "Salão de Beleza",
    "Sapateiro",
    "Saúde",
    "Seguradoras",
    "Segurança",
    "Seitai",
    "Serralheria",
    "Servente",
    "Serviços",
    "Shiatsu",
    "Sítios e Chácaras",
    "Sociólogo",
    "Sorveterias",
    "SPA",
    "Stands Automóveis",
    "Supermercados",
    "Tabelião",
    "Taxista",
    "Teatro",
    "Técnico em contabilidade",
    "Telecomunicações",
    "Televisão",
    "Terapeuta Holístico",
    "Terapeuta Sexual",
    "Terapeutas",
    "Toldos",
    "Topógrafo",
    "Tradutor",
    "Transportes",
    "Urologista",
    "Vendedores",
    "Veterinário",
    "Vidraceiros",
    "Web Design",
    "Websites",
    "Yoga",
    "Zoólogo",
];